# Site settings
title: Adam - Front-End Developer
email: whackyapple@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Web journal. Writing about front-end development, web standards, 
  Responsive and mobile-first design.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://adamfredie.github.io" # the base hostname & protocol for your site
twitter_username: adamfredie
github_username:  adamfredie

# Build settings
markdown: kramdown
